### ISSUE TITLE
Failing Unit Test: IncreaseWorksOnNegativeValues and DecreaseWorksOnNegativeValues

### ISSUE THREAD

**Issue by elisedaurio** [egruber/rpg-npc-creator#30]
Test Name:  IncreaseWorksOnNegativeValues
Test FullName:  NUnit.Framework.Tests.StatUnitTest.IncreaseWorksOnNegativeValues
Test Source:    C:\Users\Eric\Source\Repos\rpg-npc-creator\rpg-npc-creator\rpg-npc-creator\StatUnitTest.cs : line 92
Test Outcome:   Failed
Test Duration:  0:00:00.006

Result StackTrace:  at NUnit.Framework.Tests.StatUnitTest.IncreaseWorksOnNegativeValues() in C:\Users\Eric\Source\Repos\rpg-npc-creator\rpg-npc-creator\rpg-npc-creator\StatUnitTest.cs:line 98
Result Message: 
Expected: 0
  But was:  1
Result StandardOutput:  New stat New Stat created with value 1.

**Comment by elisedaurio** [comment]
Also reproduces with Decrease:
Test Name:  DecreaseWorksOnNegativeValues
Test FullName:  NUnit.Framework.Tests.StatUnitTest.DecreaseWorksOnNegativeValues
Test Source:    C:\Users\Eric\Source\Repos\rpg-npc-creator\rpg-npc-creator\rpg-npc-creator\StatUnitTest.cs : line 102
Test Outcome:   Failed
Test Duration:  0:00:00.007

Result StackTrace:  at NUnit.Framework.Tests.StatUnitTest.DecreaseWorksOnNegativeValues() in C:\Users\Eric\Source\Repos\rpg-npc-creator\rpg-npc-creator\rpg-npc-creator\StatUnitTest.cs:line 108
Result Message: 
Expected: -2
  But was:  -1
Result StandardOutput:  New stat New Stat created with value 1.

**Comment by elisedaurio** [comment]
------ Run test started ------
NUnit Adapter 3.4.0.0: Test execution started
Running all tests in C:\Users\Eric\Source\Repos\rpg-npc-creator\rpg-npc-creator\rpg-npc-creator\bin\Debug\rpg-npc-creator.exe
NUnit3TestExecutor converted 15 of 15 NUnit test cases
NUnit Adapter 3.4.0.0: Test execution complete
========== Run test finished: 15 run (0:00:00.8588553) ==========

Unit tests passing. Issue resolved
